-- ============================================================
-- MINI ATTENDANCE MANAGEMENT SYSTEM
-- Database Schema Script
-- ============================================================
-- Database engine: PostgreSQL (developed/tested against
-- postgres:16-alpine per docker-compose.yml)
--
-- This script represents the CURRENT schema as defined by:
--   - backend/app/db/models/user.py
--   - backend/app/db/models/department.py
--   - backend/app/db/models/employee.py
--   - backend/app/db/models/attendance.py
--   - backend/alembic/versions/001_initial_schema.py
--   - backend/alembic/versions/002_rename_employee_id.py
--
-- Migration 002 renames employees.employee_code to
-- employees.employee_id. This script reflects the current
-- application schema after that migration.
--
-- No application source code was modified to produce this script.
-- ============================================================


-- ============================================================
-- SECTION 1: SCHEMA
-- ============================================================


-- ------------------------------------------------------------
-- Table: users
-- Application login accounts (NOT employees).
--
-- Two roles are permitted at the database level: ADMIN and HR.
-- Role-based authorization is enforced at the application layer.
-- ADMIN and HR currently share identical permissions across all
-- protected endpoints.
-- ------------------------------------------------------------
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username        VARCHAR(50)  NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    role            VARCHAR(20)  NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'HR'))
);


-- ------------------------------------------------------------
-- Table: departments
-- Organizational divisions that employees belong to.
-- ------------------------------------------------------------
CREATE TABLE departments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(100) NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_departments PRIMARY KEY (id),
    CONSTRAINT uq_departments_name UNIQUE (name)
);


-- ------------------------------------------------------------
-- Table: employees
--
-- "id" is the internal primary key referenced by foreign keys
-- such as attendance.employee_id.
--
-- "employee_id" is the separate, human-facing business code
-- (for example, 'EMP001') used for lookups, search, and display.
-- It is NOT used as a foreign key target anywhere in this schema.
--
-- Column history:
-- The column was named "employee_code" in the initial migration
-- (001) and renamed to "employee_id" in migration 002.
-- This script reflects the current post-migration schema.
-- ------------------------------------------------------------
CREATE TABLE employees (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_id     VARCHAR(20)  NOT NULL,
    name            VARCHAR(100) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    mobile          VARCHAR(20),
    department_id   BIGINT       NOT NULL,
    designation     VARCHAR(100) NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_employees PRIMARY KEY (id),
    CONSTRAINT uq_employees_employee_id UNIQUE (employee_id),
    CONSTRAINT fk_employees_department_id
        FOREIGN KEY (department_id)
        REFERENCES departments (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_employees_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX ix_employees_department_id
    ON employees (department_id);

-- Case-insensitive uniqueness on email.
-- This is a functional unique index because the uniqueness
-- requirement applies to lower(email), not the raw email value.
CREATE UNIQUE INDEX ix_employees_lower_email
    ON employees (lower(email));


-- ------------------------------------------------------------
-- Table: attendance
--
-- One row = one employee attendance record for one date,
-- containing a check-in time and an optional check-out time.
--
-- IMPORTANT: There is NO status column on this table.
--
-- PRESENT / ABSENT is NOT stored. It is computed at query time:
--
--   - A row existing for (employee_id, attendance_date) = PRESENT
--   - An ACTIVE employee with no row for a given date = ABSENT
--
-- Do not add a status column here; it would not match the actual
-- application implementation.
-- ------------------------------------------------------------
CREATE TABLE attendance (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_id         BIGINT      NOT NULL,
    attendance_date     DATE        NOT NULL,
    check_in            TIMESTAMPTZ NOT NULL,
    check_out           TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_attendance PRIMARY KEY (id),
    CONSTRAINT fk_attendance_employee_id
        FOREIGN KEY (employee_id)
        REFERENCES employees (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_attendance_employee_date
        UNIQUE (employee_id, attendance_date),
    CONSTRAINT ck_attendance_checkout_after_checkin
        CHECK (check_out IS NULL OR check_out > check_in)
);

CREATE INDEX ix_attendance_attendance_date
    ON attendance (attendance_date);


-- ============================================================
-- SECTION 2: OPTIONAL DEVELOPMENT SEED DATA
-- ============================================================
--
-- No user seed is included because password_hash must be
-- generated using the application's password hashing utility.
--
-- The following sample records are optional development data
-- and can be skipped entirely.
-- ============================================================


-- Optional: sample departments
--
-- These names match the department definitions used by the
-- frontend. They are development convenience data and are not
-- required by the schema itself.
--
-- INSERT INTO departments (name) VALUES
--     ('Engineering'),
--     ('Human Resources'),
--     ('Finance');


-- Optional: sample employee
--
-- This assumes the Engineering department has been inserted
-- using the statement above. Adjust the department lookup if
-- using different department data.
--
-- INSERT INTO employees (
--     employee_id,
--     name,
--     email,
--     mobile,
--     department_id,
--     designation,
--     status
-- ) VALUES (
--     'EMP001',
--     'Jane Doe',
--     'jane.doe@example.com',
--     NULL,
--     (SELECT id FROM departments WHERE name = 'Engineering'),
--     'Software Engineer',
--     'ACTIVE'
-- );


-- ============================================================
-- END OF SCRIPT
-- ============================================================